// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }


// import "./globals.css";
// import { Inter } from "next/font/google";
// import { Providers } from "@/app/providers"; // Add NextAuth Provider
// import { Toaster } from "sonner";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Gym Management System",
//   description: "Manage gyms and members",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Providers>{children}</Providers>
//         <Toaster position="top-right" richColors />
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/app/providers";      // your existing auth / other providers
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider"; // ← new

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gym Management System",
  description: "Manage gyms and members",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <Providers>{children}</Providers>
          <Toaster position="top-right" richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}